name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 202.61.247.164
          username: leupold
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/biberna-logistics
            git pull

